batch_size: 512
ce_weight: 1.0
checkpoint_metric: perplexity
cuda: 1
device: cuda
encoder_depth: 3
encoder_size: 32
epoch: -1
experiment_name: E003_XKCDModel_calibrated
hparams_load_path: ../configs/E003_XKCDModel_calibrated.yaml
index: 0
input_size: 54
learning_rate: 0.01
num_epochs: 200
patience_threshold: 4
prediction_size: 829
root_output_path: /r/code/paper_repos/speaker_strategies_sigdial2020/lab/XKCD_model/logs
seed: 1337
split: unset
teacher_phi_path: /r/code/paper_repos/speaker_strategies_sigdial2020/lab/XKCD_model/logs/E002_calibrations/99th_percentile/calibrated_phis_99percentile.npy
teacher_phi_weight: 1.0
timestamp: 1591285837.294346
trial_name: published_version
trial_path: /r/code/paper_repos/speaker_strategies_sigdial2020/lab/XKCD_model/logs/E003_XKCDModel_calibrated/published_version
use_ce: 1
use_teacher_phi: 1
weight_decay: 0.0
xkcd_coordinate_system: fft
