# Experiment Hyper Params
experiment_name: E003_XKCDModel_calibrated
trial_name: published_version
root_output_path: "{LAB_SUBDIR_ROOT}/logs"
xkcd_coordinate_system: fft
teacher_phi_path: "{LAB_SUBDIR_ROOT}/logs/E002_calibrations/99th_percentile/calibrated_phis_99percentile.npy"

        
# Training Hyper Params
seed: 1337
num_epochs: 200
batch_size: 512
checkpoint_metric: perplexity
learning_rate: 0.01
patience_threshold: 4
# loss: language modeling / cross entropy
use_ce: true
ce_weight: 1.0
# loss: teacher phi / calibration
use_teacher_phi: true
teacher_phi_weight: 1.0
# overall l2
weight_decay: 0.000

# Model Hyper Params
input_size: -1
encoder_size: 32
encoder_depth: 3
prediction_size: -1

# Runtime params
cuda: true 