batch_size: 256
checkpoint_metric: perplexity
cuda: 1
device: cuda
encoder_depth: 3
encoder_size: 32
epoch: -1
experiment_name: E001_XKCDModel_uncalibrated
hparams_load_path: ../configs/E001_XKCDModel_uncalibrated.yaml
index: 0
input_size: 54
learning_rate: 0.01
num_epochs: 200
patience_threshold: 4
prediction_size: 829
root_output_path: /r/code/paper_repos/speaker_strategies_sigdial2020/lab/XKCD_model/logs
seed: 1337
split: unset
timestamp: 1591284993.3413968
trial_name: published_version
trial_path: /r/code/paper_repos/speaker_strategies_sigdial2020/lab/XKCD_model/logs/E001_XKCDModel_uncalibrated/published_version
weight_decay: 0.0
xkcd_coordinate_system: fft
